apiVersion: 1
datasources:
  - name: aw-central
    uid: aw-central
    type: postgres
    access: proxy
    url: aw-db:5432
    user: aw
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: aw
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
